DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGSERIAL PRIMARY KEY,
    GENRE_TITLE VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
  CREATE TABLE BOOKS
  (
      ID   BIGSERIAL PRIMARY KEY,
      TITLE VARCHAR(255),
      author_id BIGINT,
      genre_id BIGINT,
      FOREIGN KEY (author_id)  REFERENCES AUTHORS (Id),
      FOREIGN KEY (genre_id)  REFERENCES GENRES(Id)
  );

DROP TABLE IF EXISTS COMMENTS;
  CREATE TABLE COMMENTS
  (
      ID   BIGSERIAL PRIMARY KEY,
      CONTENT VARCHAR(1000),
      book_id BIGINT,
      FOREIGN KEY (book_id)  REFERENCES BOOKS (Id)
  );








